// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlWK5en3TQm_xEVL99i2B5Z62P8poTt58',
    appId: '1:754419896031:web:f8f8b06672e9ed5b16636a',
    messagingSenderId: '754419896031',
    projectId: 'cards-ics3u',
    authDomain: 'cards-ics3u.firebaseapp.com',
    storageBucket: 'cards-ics3u.appspot.com',
    measurementId: 'G-HFEW7J11VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdwp78H3bvv7rgk86KEojP0C3GicEthFI',
    appId: '1:754419896031:android:5cefd9daa3850def16636a',
    messagingSenderId: '754419896031',
    projectId: 'cards-ics3u',
    storageBucket: 'cards-ics3u.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPM6tI9v8J4eZgh0UbFbiabRUCiNQHSxc',
    appId: '1:754419896031:ios:72d21040080256dc16636a',
    messagingSenderId: '754419896031',
    projectId: 'cards-ics3u',
    storageBucket: 'cards-ics3u.appspot.com',
    iosClientId: '754419896031-38s316q1o6aiccu6opgfjgpa5unundmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.overlay',
  );
}
